# Generated by Django 4.2.30 on 2026-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='riders_dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickuplocation', models.CharField(max_length=200)),
                ('droplocation', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('time', models.IntegerField()),
                ('fare', models.FloatField()),
            ],
        ),
    ]
